### ISSUE TITLE
MoonNode not sending commands to moonraker

### ISSUE THREAD

**Issue by pbcrazy** [MintyTrebor/moonNode#6]
Hi Minty,

first off - thanks for your work on this. I used your duet nodes and am now trying to get your moonraker nodes working since jumping to klipper. 

Basically I am streaming all extrusion commands over node-red to moonraker. This is because I am streaming the required flow rates via TCP/IP from a robotic arm, and node-red acts as the translator to Unix/web sockets since I couldn’t figure out a direct way to stream TCP to klipper. This worked fine with the dsf nodes, but with the moonraker nodes they can’t seem to handle the large # of commands I’m sending (~50 hz). Any ideas why this might be? My flow is super simple, a tcp in to a function mode that puts the command into the ‘G1 Exxx Fxxx’ format over msg.payload.cmd. 

If I send 1 command through the format function into the moonnode, it sends fine and I can see the command show up on the moonraker/fluidd terminal. But when I start the stream, it doesn’t send any commands (at least that are executed or show up on the terminal). The first output of the cmd node also doesn’t export anything, anytime, even when just sending 1 command. Any ideas?? Super appreciated, I’ve spent a ton of time trying to work through this and have gotten nowhere. Thank you!!

**Comment by MintyTrebor** [comment]
The node behaviour was not designed to accommodate that rate, due to the way it handled the websocket connection. I have changed this is in the latest version for you. 
I have tested it streaming 390 g1 commands @ 20ms interval between each command with no issues. 
Please let me know how you get on with the update. (I am unsure how commands that trigger a response msg will impact the behaviour when sending commands at this high rate, but my limited tests showed no issues.)

**Comment by pbcrazy** [comment]
This worked great, thank you!

Do you have a way to send you a small donation for a coffee or dinner? Your work has been a hugeeee help to me!

**Comment by MintyTrebor** [comment]
Great. No donation required. But thankyou for the offer. 
Is there anywhere I can see pics/vids of your project?

**Comment by pbcrazy** [comment]
Absolutely! Do you have a discord or something I can shoot over a video to? Mine is pbcrazy#5636
